import "./globals.css";
import { Red_Hat_Display } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"

const exo = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata = {
  title: "Seoul Stream",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={exo.className}      
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
